<?php 
function tpl_542c5a09_landing__OTSuAGuUv96fK2IQmm9QAw(PHPTAL $tpl, PHPTAL_Context $ctx) {
$_thistpl = $tpl ;
$_translator = $tpl->getTranslator() ;
/* tag "documentElement" from line 1 */ ;
$ctx->setDocType('<!DOCTYPE html>',false) ;
?>

<?php /* tag "html" from line 2 */; ?>
<html lang=en>
<?php /* tag "head" from line 3 */; ?>
<head>
    <?php /* tag "meta" from line 4 */; ?>
<meta charset=utf-8>
    <?php /* tag "title" from line 5 */; ?>
<title><?php echo phptal_escape($ctx->path($ctx->meta, 'title')) ?>
</title>
    <?php /* tag "link" from line 6 */; ?>
<link rel=stylesheet href=/assets/stylesheet/base.css>
    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<?php /* tag "body" from line 11 */; ?>
<body>

<?php /* tag "script" from line 13 */; ?>
<script type=text/javascript>
    var _paq = _paq || [];
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
        var u=(("https:" == document.location.protocol) ? "https" : "http") + "://nod.agency/piwik/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', 1]);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript';
        g.defer=true; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
</script>
<?php /* tag "noscript" from line 25 */; ?>
<noscript><?php /* tag "p" from line 25 */; ?>
<p><?php /* tag "img" from line 25 */; ?>
<img src="http://nod.agency/piwik/piwik.php?idsite=1" style=border:0; alt=""></p></noscript>
</body>
</html><?php 
/* end */ ;

}

?>
<?php /* 
*** DO NOT EDIT THIS FILE ***

Generated by PHPTAL from /application/templates/landing.xhtml (edit that file instead) */; ?>